// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.lastAppBuildId", "20250821175018");
user_pref("extensions.lastAppVersion", "142.0");
user_pref("extensions.lastPlatformVersion", "142.0");
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
